### ISSUE TITLE
Ajeitar a vizualização dos trechos disponiveis

### ISSUE THREAD

**Issue by Armaaaaaaaaaaaaaaaaaaaaaaaaaaando** [fabiomirs/PBL1_TEC502#8]

**Comment by fabiomirs** [comment]
Na parte das compras, o cliente deve primeiro visualizar todas as 10 cidades disponíveis, indicar o número correspondente a cidade de origem e de destino. A partir do que for informado ele visualiza todas as rotas possíveis, escolhe a rota de acordo com uma numeração e atualiza os dados das passagens para aquela rota, considerando todos os trechos possíveis, e atualizando o número de passagens de todos.
